// Generated by Selenium IDE
const { Builder, By, Key, until } = require("selenium-webdriver");
const assert = require("assert");

describe("JogoSecreto", function () {
  this.timeout(30000);
  let driver;
  let vars;

  beforeEach(async function () {
    driver = await new Builder().forBrowser("chrome").build();
    vars = {};
  });

  afterEach(async function () {
    await driver.quit();
  });

  it("JogoSecreto", async function () {
    await driver.get("https://elisirons.github.io/jogoNumeroSecreto/");
    await driver.manage().window().setRect({ width: 974, height: 823 });
    await driver.findElement(By.css(".container__input")).sendKeys("15");
    await driver.findElement(By.css(".container__botao:nth-child(1)")).click();
    let errorMessage = await driver
      .findElement(By.css(".texto__paragrafo"))
      .getText();
    assert.strictEqual(
      errorMessage,
      "Por favor, insira um número entre 1 e 10."
    );

    await driver.findElement(By.css(".container__input")).click();
    await driver.findElement(By.css(".container__input")).sendKeys("1");
    await driver.findElement(By.css(".container__botao:nth-child(1)")).click();
    await driver.findElement(By.css(".container__input")).click();
    await driver.close();
  });
});
